### ISSUE TITLE
Prevents collision of internal cache ids when using DbSelectAdapter

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-paginator#1]
Fixes issue #41 
Fixes pull request #42 

---

Originally posted by @mariojrrc at https://github.com/zendframework/zend-paginator/pull/46

**Comment by weierophinney** [comment]
@mariojrrc 
Please look at https://github.com/zendframework/zend-paginator/issues/41#issuecomment-407798358 and leave a comment. Thanks!

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-paginator/pull/46#issuecomment-407799184

**Comment by froschdesign** [comment]
The original pull request introduced a BC break.
