### ISSUE TITLE
Does not include all dependencies

### ISSUE THREAD

**Issue by Bilge** [laminas/laminas-paginator#26]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.10.0

#### Summary

Calling `render()` throws `ClassNotFoundError`.

#### Current behavior

>Attempted to load class "PhpRenderer" from namespace "Laminas\View\Renderer".
Did you forget a "use" statement for another namespace?

#### How to reproduce

1. `composer req laminas/laminas-paginator`
2. `(new Paginator(new ArrayAdapter([])))->render()`.

#### Expected behavior

No exception. Note that not only is the default renderer (`PhpRenderer`) unavailable, neither is the `RendererInterface` that would allow one to implement their own. Being as that's the case, the library is unusable in its default installation state.

**Comment by weierophinney** [comment]
laminas-view integration is _optional_, and laminas-view itself is in the package suggestions. You can use the component without that integration.

**Comment by froschdesign** [comment]
More informations on the topic "suggested packages" can be found in the documentation of Composer: https://getcomposer.org/doc/04-schema.md#suggest

**Comment by Bilge** [comment]
What is the use case for a paginator that is never rendered?

**Comment by froschdesign** [comment]
The paginator can output the pure data: https://docs.laminas.dev/laminas-paginator/application-integration/stand-alone/#output-pure-data
And additionally, it is planned to support more than laminas-view for rendering.
