### ISSUE TITLE
Wrong automatic generating of sql for paginator?

### ISSUE THREAD

**Issue by tempfirstuser** [laminas/laminas-paginator#30]
|    Q        |   A
|------------ | ------
| Version(s)  | 2.10.0

Guys, I am not sure yet but it looks like this is a bug. Suddenly we got an error on one of our pages which uses paginator.

This is a part of exception. I think this was appear after some running `composer install` command. 

Additional information:
```
Laminas\Db\Adapter\Exception\InvalidQueryException

File:

    /vendor/laminas/laminas-db/src/Adapter/Driver/Pdo/Statement.php:243

Message:

    Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AS `original_select`' at line 1)

Stack trace:

    #0 /vendor/laminas/laminas-paginator/src/Adapter/DbSelect.php(121): Laminas\Db\Adapter\Driver\Pdo\Statement->execute()
    #1 /vendor/laminas/laminas-paginator/src/Paginator.php(920): Laminas\Paginator\Adapter\DbSelect->count()
    #2 /vendor/laminas/laminas-paginator/src/Paginator.php(589): Laminas\Paginator\Paginator->_calculatePageCount()
    #3 our internal method (55): Laminas\Paginator\Paginator->setItemCountPerPage()
    #4 
    #5 
    #6 
    #7 /vendor/laminas/laminas-eventmanager/src/EventManager.php(331): OurInternalActionController->onDispatch()
    #8 /vendor/laminas/laminas-eventmanager/src/EventManager.php(188): Laminas\EventManager\EventManager->triggerListeners()
    #9 /vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
    #10 /vendor/laminas/laminas-mvc/src/DispatchListener.php(138): Laminas\Mvc\Controller\AbstractController->dispatch()
    #11 /vendor/laminas/laminas-eventmanager/src/EventManager.php(331): Laminas\Mvc\DispatchListener->onDispatch()
    #12 /vendor/laminas/laminas-eventmanager/src/EventManager.php(188): Laminas\EventManager\EventManager->triggerListeners()
    #13 /vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
    #14 /public/index.php(48): Laminas\Mvc\Application->run()
    #15 {main}
```

`

and `original_select` is located in the file "/vendor/laminas/laminas-paginator/src/Adapter/DbSelect.php" on line 147:

`        $countSelect->from(['original_select' => $select]);
`
I just started debug but maybe you are aware of this bug?

```
SELECT "current_table".*, "b"."blog_id" AS "blog_id", "n"."news_id" AS "news_id" FROM "current_table" LEFT JOIN "blog" AS "b" ON "b"."id" = "current_table"."id" LEFT JOIN "news" AS "n" ON "n"."id" = "current_table"."id" WHERE category_id = '1' AND ()

```

**Comment by weierophinney** [comment]
Can you provide a way to reproduce, please?

- schema of the table(s) you are paginating, and some sample data
- how you are creating the `Select` instance against it
- the code creating the pagination adapter

This will help us determine if (a) a bug exists, or (b) there is an issue with how you're setting it up (which could indicate a documentation issue on our side).

Thanks!

**Comment by tempfirstuser** [comment]
@weierophinney , 10 mins. I will try to downgrade paginator versions and will give some info.

**Comment by tempfirstuser** [comment]
versions starting from 2.8 to 2.11.x-dev doesn't work. And I can't downgrade to 2.7 because of dependencies.

**Comment by froschdesign** [comment]
@tempfirstuser 
> …for the right syntax to use near ')) AS `original_select`'

Can you provide the full SQL query or the code that shows how your `Select` object is created?

**Comment by tempfirstuser** [comment]
@froschdesign , I've updated description. I hope it will be helpful.

**Comment by froschdesign** [comment]
@tempfirstuser 
> I hope it will be helpful.

Can you read it? I don't think so. 😉 

Please try the following to create the SQL query:

```php
$databaseAdapter = … // your database adapter
$select = … // your select object

$sql = new Laminas\Db\Sql\Sql($databaseAdapter);
echo $sql->buildSqlString($select);
```

**Comment by tempfirstuser** [comment]
@froschdesign , I found how to get sql string and it contains this part at the end: ` WHERE category_id = '1' AND ()` which means sql is broken.

**Comment by tempfirstuser** [comment]
@froschdesign , sorry about "machine" code. I didn't know how to get sql string from laminas-db because earlier I worked only with doctine (and Zend_Db).

**Comment by tempfirstuser** [comment]
@froschdesign , I've updated description with sql string.

**Comment by weierophinney** [comment]
@tempfirstuser Please demonstrate how you are building the query in the first place. What I'm seeing from the SQL string you've pasted, there's an invalid part to it (which you've noted: `WHERE category_id = '1' AND ()`). The question is how you're getting an empty `AND` segment, which is likely an issue with the original query generation in the first place.

Show us how you build the `$select` object, as that will likely hold the key here.

**Comment by tempfirstuser** [comment]
@weierophinney , we have this code which added `like` to the sql query:

```
function prepareSearch(Select $select ...){
    $last = $select->where->and->nest();

    foreach($columns as $column){
        $last = $last->like(...);
        $last = $last->or->like(...);
    }

    $last->unnest();
}
```

`$columns` is empty array that's why I have empty `AND ()`.  We have different similar pages with pagination and search. And I was always sure that this page had working search functionality which uses pagination. I am still new to the project and I am exploring git history of related files. It looks like search on this page never worked. I am waiting for feedback from previous developer and will have answers later. I have broken sql and this is has nothing to do with `laminas-paginator`.

But for now you can close this issue. I am really sorry for bothering you. Thank you!

**Comment by froschdesign** [comment]
@tempfirstuser 
`$select->where->and->nest();` adds `AND (`
`$last->unnest();` adds `)`

So the entire block must be omitted if `$columns` is empty.

> But for now you can close this issue.

Notice: When you open a issue report or pull request, you can also close it yourself.

> I am really sorry for bothering you.

No problem and if you have more questions, you can use the forum or chat: https://getlaminas.org/participate/
